// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WahsKeyClubSite.Models;

namespace WahsKeyClubSite.Migrations.ServiceHoursDb
{
    [DbContext(typeof(ServiceHoursDbContext))]
    partial class ServiceHoursDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WahsKeyClubSite.Models.ServiceHours", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activity")
                        .IsRequired();

                    b.Property<DateTime>("DateOfActivity");

                    b.Property<DateTime>("DateSubmitted");

                    b.Property<double>("Hours");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.ToTable("ServiceHours");
                });
#pragma warning restore 612, 618
        }
    }
}
